name: Build PSP EBOOT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - uses: actions/checkout@v4

      - name: Fix git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Debug source
        run: |
          git rev-parse HEAD
          sed -n '80,95p' src/audio/mic.c
          sed -n '65,115p' src/network/http_client.c

      - name: Build
        run: |
          make clean || true
          make

      - uses: actions/upload-artifact@v4
        with:
          name: EBOOT_PBP
          path: EBOOT.PBP
          if-no-files-found: error
